"""add phone_number to user

Revision ID: 53fe63ff107b
Revises: cad6836f0b93
Create Date: 2026-04-15 11:28:34.863214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '53fe63ff107b'
down_revision: Union[str, Sequence[str], None] = 'cad6836f0b93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment', sa.Column('home_pos', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography'), nullable=True))
    op.execute("UPDATE equipment SET home_pos = current_pos WHERE current_pos IS NOT NULL")
    op.alter_column('equipment', 'home_pos', nullable=False)
    op.execute("DROP INDEX IF EXISTS idx_equipment_current_pos")
    op.execute("CREATE INDEX IF NOT EXISTS idx_equipment_home_pos ON equipment USING gist (home_pos)")
    op.drop_column('equipment', 'current_pos')
    op.add_column('user', sa.Column('phone_number', sa.String(length=10), nullable=True))
    op.execute("UPDATE \"user\" SET phone_number = '00000000' WHERE phone_number IS NULL")
    op.alter_column('user', 'phone_number', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'phone_number')
    op.add_column('equipment', sa.Column('current_pos', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', _spatial_index_reflected=True), autoincrement=False, nullable=True))
    op.execute("UPDATE equipment SET current_pos = home_pos WHERE home_pos IS NOT NULL")
    op.alter_column('equipment', 'current_pos', nullable=False)
    op.execute("DROP INDEX IF EXISTS idx_equipment_home_pos")
    op.execute("CREATE INDEX IF NOT EXISTS idx_equipment_current_pos ON equipment USING gist (current_pos)")
    op.drop_column('equipment', 'home_pos')
    # ### end Alembic commands ###
