"""updated equipment table

Revision ID: a2859953ce97
Revises: b287500cf2bc
Create Date: 2026-03-03 13:20:08.062708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2859953ce97'
down_revision: Union[str, Sequence[str], None] = 'b287500cf2bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment', sa.Column('owner_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'equipment', 'group', ['owner_id'], ['id'])
    op.drop_column('equipment', 'owner')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment', sa.Column('owner', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'equipment', type_='foreignkey')
    op.drop_column('equipment', 'owner_id')
    # ### end Alembic commands ###
